---
title: "Signficane Testing"
output: html_document
---

# Initialize

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}

#install.packages("tidyverse")
library(tidyverse)

```


# Load Data


```{r load data}

wbb <- 
  read_csv(
    url("https://raw.githubusercontent.com/matsonah/ClarkeStatsFall2022/main/AssignedRStudioProjects/WBB%20Stats.csv"), 
    show_col_types =F)   #Try out different years

names(wbb)
# Read about calculations: https://www.gov.uk/guidance/making-your-gender-pay-gap-calculations#overview 
backup <- wbb 

```

## Substring


```{r alter}

wbb <- 
  wbb %>% 
    mutate( verdict =  
              case_when(
                str_detect(SCORE, "W")~ "W",
                str_detect(SCORE, "L") ~ "L",
                T ~ "Other"
              )
            )

```

## Quantitative Boundary


```{r}

wbb <- 
  wbb %>% 
    mutate( compare =  
              case_when(
                OFF > 10~ T, 
                T ~ F 
              )
            )

```

## Multiple Quantitative Boundaries

```{r}

wbb <- 
  wbb %>% 
    mutate( compare2 =  
              case_when(
                OFF > 10~  "high", 
                OFF > 5 ~ "medium", 
                T ~ "low"
              )
            )

```


# Data Play 

```{r}

wbb %>% 
  ggplot( aes(x=OFF, colour = compare2, fill=compare2)) + 
    labs(
      x="OFF",
      y="proportion", 
      title="2020-2021 Women's Basketball"
    ) + 
    stat_ecdf()

```
